---
# Run when PRs to main are closed.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

name: Build and publish a release

jobs:
  # We make `if_merged` a `needs:` of the other jobs here to only run this
  # workflow on merged PRs.
  if_merged:
    name: Check that PR was merged and not closed
    if: github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is a canonical hack to run GitHub Actions on merged PRs"
          echo "See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges"

      - name: Comment on PR with link to this action
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [This release is now being built.][run]

            [run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  version:
    name: Get version number
    needs: if_merged
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_project_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: accept-flake-config = true

      - name: Get version number
        id: get_project_version
        run: echo "version=$(nix run .#get-project-version)" >> "$GITHUB_OUTPUT"

  pypi-publish:
    name: Upload release to PyPI
    needs: if_merged
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # This permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: accept-flake-config = true

      - name: Build wheel and sdist
        run: nix build .#argparse-pydantic.dist --print-build-logs --out-link dist

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "dist/*"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  upload:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs:
      - if_merged
      - pypi-publish
      - version
    steps:
      - name: Tag the release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
          custom_tag: ${{ needs.version.outputs.version }}

      - name: Download artifacts
        # This downloads the uploaded artifacts to the current directory; the
        # path format for downloaded artifacts is `{name}/{basename}`, where
        # `{basename}` is the basename of the upload `path`.
        #
        # For example, the following artifact:
        #
        #     - uses: actions/upload-artifact@v3
        #       with:
        #         name: dist
        #         path: result/argparse_pydantic-1.0.0-py3-none-any.whl
        #
        # will be downloaded to `dist/argparse_pydantic-1.0.0-py3-none-any.whl`.
        uses: actions/download-artifact@v3

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ needs.version.outputs.version }}
          files: |
            dist/*

      - name: Comment on PR with link to the release
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [Release ${{ needs.version.outputs.version }}][release] was built and published successfully!

            [release]: ${{ steps.create_release.outputs.url }}
